-- Spring Security OAuth2 authorized client table (PostgreSQL-compatible DDL).
-- DDL source: org/springframework/security/oauth2/client/oauth2-client-schema.sql
CREATE TABLE IF NOT EXISTS oauth2_authorized_client (
    client_registration_id  VARCHAR(100) NOT NULL,
    principal_name           VARCHAR(200) NOT NULL,
    access_token_type        VARCHAR(100) NOT NULL,
    access_token_value       BYTEA        NOT NULL,
    access_token_issued_at   TIMESTAMP    NOT NULL,
    access_token_expires_at  TIMESTAMP    NOT NULL,
    access_token_scopes      VARCHAR(1000) DEFAULT NULL,
    refresh_token_value      BYTEA        DEFAULT NULL,
    refresh_token_issued_at  TIMESTAMP    DEFAULT NULL,
    created_at               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (client_registration_id, principal_name)
);

CREATE TABLE IF NOT EXISTS app_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spotify_id   VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    email        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_log (
    id           UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      BIGINT NOT NULL REFERENCES app_user(id),
    user_message TEXT   NOT NULL,
    response     TEXT,
    created_at   TIMESTAMP DEFAULT now()
);

-- Requires pgvector extension; use the pgvector/pgvector:pg16 Docker image in dev.
-- HNSW index chosen over IVFFlat: IVFFlat requires ~3900 rows for reliable probing,
-- which exceeds typical per-user library sizes (200-2000 tracks). HNSW works well
-- at any cardinality. m=16 and ef_construction=64 are the pgvector-recommended defaults.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS track_embedding (
    id               UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          BIGINT  NOT NULL REFERENCES app_user(id),
    spotify_track_id TEXT    NOT NULL,
    track_text       TEXT    NOT NULL,
    embedding        vector(1536),
    playlist_names   TEXT,
    last_updated     TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (user_id, spotify_track_id)
);

CREATE INDEX IF NOT EXISTS track_embedding_hnsw_idx
    ON track_embedding USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS user_chat_placeholder_preferences (
    user_id                   BIGINT PRIMARY KEY REFERENCES app_user(id),
    placeholder_mood          TEXT,
    placeholder_playlist      TEXT,
    placeholder_feeling       TEXT,
    placeholder_generated_at  TIMESTAMP
);
